# copy此文件为server.yaml，对应修改配置
port: 4000
apiPrefix: api
corsOrigin: localhost
authApi: "http://192.168.21.176:3000/api/"
shareApi: "http://192.168.21.176:4005/api/"
shareToken: "Bearer 85e47ac07ac9d6416168a97e33fa969a"
adminUserId: "81"
adminGroupName: wiki
ssoApi: "https://sso.3dlink.cn/api/"
# isAutoSyncEsFromMongoWhenStart: true
isAutoSendExpiredEnterpriseWechatShare: true
esBackupDays: 3
searchApi: "http://10.100.30.65:8080/"
#mingdao:
#  url: "https://api.mingdao.com/workflow/hooks/xxx"
draft:
  backupDays: 90
  backupNoBlogDays: 30
  backupCount: 10
kafka:
  clientId: "wiki"
  emailTopic: "emails"
  msgTopic: "notification"
  groupId: "wiki"
  docsTopic: "docs"
  brokers:
    - "192.168.21.125:30090"
    - "192.168.21.125:30091"
    - "192.168.21.125:30092"
db: mongodb://192.168.21.176:27018/wiki
redis:
  port: 6379
  host: localhost
  password: xxxx
  db: 0

tag:
  maxTagLength: 30
  minTagLength: 1
  tagReg: ^[\u4E00-\u9FA5\w\s-]+$
  tagRegErrMsg: 标签只允许中文、英文、数字、空格、_和-

showId:
  reg: ^[A-Za-z0-9]+[\w-]*$
  regErrMsg: showId只允许英文、数字_和-，且不能以_或-开头
  maxLength: 50
  mongoSameIdErrMsg: "showId不能设置mongo一样类型的id"
group:
  fine: "fine"
  transUser: "transUser"
  integral: "integral"
  top: "top"
  share: "share"
  token: "token"
  publishToOfficial: "official"
  public: "public"
  checkPublic: "checkPublic"
log:
  appenders:
    dateFile:
      filename: logs/deno
      daysToKeep: 10
      pattern: yyyy-MM-dd.log
  categories:
    default:
      appenders:
        - dateFile
        - console
      level: DEBUG
