# 使用用户名和组名设置容器内进程的用户和组
version: '3'
services:
  nginx:
    image: nginx
    user: root
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../Page:/usr/share/nginx/html